### ISSUE TITLE
undefined method getName()

### ISSUE THREAD

**Issue by rezanadimi72** [yiisoft/yii-queue-amqp#45]
hi 
i see a bug in `vendor/yiisoft/yii-queue-amqp/src/MessageSerializer.php` line 24
this line use
`$message->getName(),` 
but this method not found in `vendor/yiisoft/yii-queue/src/Message/MessageInterface.php` interface
just exist `getHandlerName()` method
please fix it
thank you

**Comment by terabytesoftw** [comment]
Thank you, if you have time you could do a PR.

**Comment by rezanadimi72** [comment]
ok
no problem

**Comment by viktorprogger** [comment]
Fixed

**Comment by rezanadimi72** [comment]
@viktorprogger 
thank you
