### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by viktorprogger** [yiisoft/yii-queue-amqp#5]

**Comment by s1lver** [comment]
Someone is doing this?

**Comment by viktorprogger** [comment]
Nope, feel free to make a PR

**Comment by samdark** [comment]
@s1lver still want to take it?

**Comment by s1lver** [comment]
I made tests run under different php version for local testing, but  im busy now rr)

**Comment by s1lver** [comment]
not stable test `Yiisoft\Yii\Queue\AMQP\Tests\Integration\DelayMiddlewareTest::testMainFlow`
