### ISSUE TITLE
Namespace naming convention

### ISSUE THREAD

**Issue by rustamwin** [yiisoft/yii-queue-amqp#7]
I think that `Driver` should be removed from the namespace.

**Comment by viktorprogger** [comment]
I think this element makes sense for understanding what class are you going to use. But yes, this package has 2 new namespace elements against `yiispft/yii-queue`.

**Comment by viktorprogger** [comment]
Another thing is [SynchronousDriver](https://github.com/yiisoft/yii-queue/blob/master/src/Driver/SynchronousDriver.php) is under `Driver` namespace too.

**Comment by rustamwin** [comment]
> Another thing is SynchronousDriver is under Driver namespace too.

Because it is located in the `Driver` directory. I'd suggest removing `Driver` from the [root namespace](https://github.com/yiisoft/yii-queue-amqp/blob/79b3e41db75b5b7f1f69b4da6ad8f343d25a5ee1/composer.json#L35) and moving the driver class to the `Driver` directory.

**Comment by samdark** [comment]
Yes. It should be adjusted according to https://github.com/yiisoft/docs/blob/master/004-namespaces.md
